apiVersion: apps/v1
kind: Deployment
metadata:
  name: private
  labels:
    app: private
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private
  template:
    metadata:
      labels:
        app: private
    spec:
      containers:
      - image: k8s.gcr.io/git-sync:v3.0.1
        name: private
        volumeMounts:
        - name: html
          mountPath: /tmp/git
        env:
        - name: GIT_SYNC_REPO
          value: https://github.com/gh-bdr/private-git-sync.git
        - name: GIT_SYNC_BRANCH
          value: main
        - name: GIT_SYNC_DEST
          value: "html"
        - name: GIT_SYNC_USERNAME
          value: "gh-bdr"
        - name: GIT_SYNC_PASSWORD
          value: ""    #access token for github
      - name: nginx-private
        image: nginx
        ports:
          - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx
      volumes:
      - name: html
        emptyDir: {}
      - name: git-secret
        secret:
          secretName: git-creds
          defaultMode: 256

--- 

apiVersion: v1
kind: Service
metadata:
  name: svc-private
spec:
  type: NodePort
  selector:
    app: private
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30010
